export const MemeTypes = {
    POST_MEME_REQUEST: 'POST_MEME_REQUEST',
    POST_MEME_ERROR: 'POST_MEME_ERROR',
    POST_MEME_SUCCESS: 'POST_MEME_SUCCESS',
    GET_MEMES_REQUEST: 'GET_MEMES_REQUEST',
    GET_MEMES_ERROR: 'GET_MEMES_ERROR',
    GET_MEMES_SUCCESS: 'GET_MEMES_SUCCESS',
}
