export const AuthTypes = {
    // SIGN UP
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    // SIGN OUT
    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',
    SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',
}
