export const UserTypes = {
    SET_USER: 'SET_USER',
    GET_USER: 'GET_USER',
    GET_USER_ERROR: 'GET_USER_ERROR',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
}
